name: Build Radar

on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Generate Radar
        run: |
          npm i
          node transform.js
          mkdir ../out
          cp radar.csv ../out/radar.csv
          mkdir ../radar
          cd ../radar
