name: Deploy AZ Static Webapp

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/az-static-webapp/**'
      - '.github/workflows/deploy-sitecoreradarredirects.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Config
      id: deployconfig
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZ_SITECORERADARREDIRECTS_DEPLOY_TOKEN }}
        action: "upload"
        app_location: "src/az-static-webapp" # App source code path relative to repository root
