name: CI
env:
  RADAR_BRANCH: "radar"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Generate Radar
        run: |
          npm i
          node transform.js
          mkdir ../out
          cp radar.csv ../out/radar.csv
          mkdir ../radar
          cd ../radar

      - uses: actions/checkout@v2
        with:
          ref: ${{env.RADAR_BRANCH}}

      - name: Prepare Radar Artifact
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ls -al
          mkdir ./latest
          cp ../out/radar.csv ./latest/radar.csv

      - name: Commit Radar
        run: |
          git add .
          git commit -m 'Radar Updated by GH Action' -a

      - name: Push Radar
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{env.RADAR_BRANCH}}
