name: Build and Publish
env:
  RADAR_BRANCH: "radar"
  RADAR_FILENAME: "Sitecore Radar.csv"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Generate Radar
        run: |
          npm i
          node transform.js
          mkdir ../out
          mv radar.csv ../out/radar.csv
          mkdir ../radar
          cd ../radar

      - uses: actions/checkout@v2
        with:
          ref: ${{ env.RADAR_BRANCH }}

      - name: Prepare Radar Artifact
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mv ../out/radar.csv "./latest/${{ env.RADAR_FILENAME }}"

      - name: Commit Radar
        run: |
          git add .
          git commit -m 'Radar Updated by GH Action' -a

      - name: Push Radar
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RADAR_BRANCH }}
